version: '3.7'
networks:
    db_network:
        name: db_network
services:
    web: 
        image: aalgard/text_to_vote:latest
        volumes:
            - ".:/app"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - "80:80"
        networks: 
            db_network:
                aliases: 
                    - mysql
     
    db:
        image: aalgard/cust_mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - "3306:3306"
        networks: 
            db_network:
                aliases: 
                    - mysql

